[package]
name = "despicable-socks5"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
tracing = "0.1.32"

[dependencies.tokio]
version = "1.17.0"
features = ["rt", "net", "io-util"]